### ISSUE TITLE
БД

### ISSUE THREAD

**Issue by MrLusiusi** [moroz-alex/autoservice#4]
Здравствуйте! Занимаюсь сейчас разработкой сайта автосервиса и нашел Ваш проект и это просто пример идеального функционала личного кабинета! Подскажите пожалуйста, возможно я не выполнил какие-то шаги, либо БД не заполнилась почему-то. Можно Вас попросить пожалуйста обновить заполнение БД ? Потому что у меня заполнились только таблицы settings и states. И если есть возможность, можно ли узнать пожалуйста по каким курсам вы обучались или может есть какие-то определенные YouTube каналы, которые могли бы выделить как фавориты для обучения ?

**Comment by moroz-alex** [comment]
Здравствуйте! Спасибо за отзыв)
Насчет заполнения БД - все верно, так и должно быть. Далее необходимо зарегистрироваться на Auto RIA (раздел для разработчиков - developers.ria.com) чтобы получить API-ключ. Вставьте полученный ключ в поле "API ключ сервиса AUTO RIA" в настройках автосервиса. Затем в разделе "Марки и модели авто" нажмите кнопку "Обновить список всех марок и моделей" - будут заполнены таблицы brands и car_models (процесс реализован с использованием очередей, подождите несколько минут).
Остальные таблицы (masters, tasks, orders, schedules и т.д.) заполняются в процессе эксплуатации администратором и/или менеджером. Т.е. администратор создает список работ и их категорий в соответствии с потребностями конкретной организации, добавляет менеджеров, мастеров; менеджер - добавляет клиентов и создает заказы.
Из курсов могу посоветовать вот этот канал: https://www.youtube.com/channel/UCoRK0WG_XW1l1CqlGC-Mg_w/playlists

**Comment by hikiasi** [comment]
> Здравствуйте! Спасибо за отзыв)
> 
> Насчет заполнения БД - все верно, так и должно быть. Далее необходимо зарегистрироваться на Auto RIA (раздел для разработчиков - developers.ria.com) чтобы получить API-ключ. Вставьте полученный ключ в поле "API ключ сервиса AUTO RIA" в настройках автосервиса. Затем в разделе "Марки и модели авто" нажмите кнопку "Обновить список всех марок и моделей" - будут заполнены таблицы brands и car_models (процесс реализован с использованием очередей, подождите несколько минут).
> 
> Остальные таблицы (masters, tasks, orders, schedules и т.д.) заполняются в процессе эксплуатации администратором и/или менеджером. Т.е. администратор создает список работ и их категорий в соответствии с потребностями конкретной организации, добавляет менеджеров, мастеров; менеджер - добавляет клиентов и создает заказы.
> 
> Из курсов могу посоветовать вот этот канал: https://www.youtube.com/channel/UCoRK0WG_XW1l1CqlGC-Mg_w/playlists

Спасибо большое за объяснение работы проекта!! И отдельное спасибо за канал, буду изучать) а роли в users какие присутствуют ? То есть как их правильно записать в бд, чтобы зарегистрировать к примеру администратора и менеджера ?

**Comment by moroz-alex** [comment]
Да, к сожалению я не учел в мануале процесс добавления первого администратора...
Самый простой способ - после установки прямо с главной страницы зарегистрируйте нового пользователя (ссылка "Зарегистрироваться" в правом верхнем углу), затем прямо в БД в таблице users измените этому пользователю поле role на 2. При регистрации указывайте реальный емейл - на него придет ссылка для подтверждения аккаунта (вы же прописали в .env настройки почты?)
После этого залогиньтесь под созданным админом и прямо в админке (раздел "Пользователи") можете добавлять новых пользователей с нужными ролями (клиент, менеджер или администратор).

**Comment by hikiasi** [comment]
> Да, к сожалению я не учел в мануале процесс добавления первого администратора... Самый простой способ - после установки прямо с главной страницы зарегистрируйте нового пользователя (ссылка "Зарегистрироваться" в правом верхнем углу), затем прямо в БД в таблице users измените этому пользователю поле role на 2. При регистрации указывайте реальный емейл - на него придет ссылка для подтверждения аккаунта (вы же прописали в .env настройки почты?) После этого залогиньтесь под созданным админом и прямо в админке (раздел "Пользователи") можете добавлять новых пользователей с нужными ролями (клиент, менеджер или администратор).

Да, указывал. Спасибо большое за объяснение!!!
